### ISSUE TITLE
Drive filling up

### ISSUE THREAD

**Issue by rtgoodwin** [milesburton/teslacam#18]
Using the newly merged Docker functionality, Pi Zero W, and 64GB microSD. 

What I'm seeing is that the drive _is_ showing up as a drive, and rsync'ing data, but is not cleaning up apparently. Twice the SD has completely filled, and once it got down to 1.2GB available and stopped showing up as a drive. 

In this last instance I SSH in, and try to attach to the docker cleaner container, and it took a while, then printed:

`Running  [find /video/RecentClips -mtime +2 -type f -delete]`

I tried cleaning off a bunch of RecentClips, and nothing changed in the output (stayed attached). `top` doesn't show anything as consistently using a lot of CPU. 

Not sure how to debug this one, honestly, but overall the Docker structure is working...once the cleanup works! :)

**Comment by wurmr** [comment]
Is it RecentClips or SavedClips that is filling?

Perhaps with your driving habits 2 days of driving data is too much for you to keep for a 64gb card. You could try a smaller number.

Try the `NUMBER_OF_DAYS_TO_KEEP` environment variable on the clip-cleaner container to a lower number.

Here is the snippet from the installation script
```
    docker run \
    --restart=always \
    -d \
    -v /home/pi/teslacam/video:/video \
    -e "NUMBER_OF_DAYS_TO_KEEP=2" \
    --name clean-recent-clips \
    teslacam/clean-recent-clips
```

**Comment by rtgoodwin** [comment]
This was from a fresh wipe to full over about 2 days, in Recent Clips I think but I hadn't looked to see if it was the virtual disks or real disks with the problem. I spent maybe 2.5 total hours on the road over this time, with somewhere between 8-12 Sentry events. (Lots of people walking through parking lot.) The files were all 8-24 and 8-25 dates, so I'm guessing it's somehow filling up before it can be pruned. 

Of note, sitting yesterday typing the bug, the virtual drive dropped offline. (Plugged into Macbook). 

Right now:
```
/dev/root        59G   21G   36G  37% /
devtmpfs        213M     0  213M   0% /dev
tmpfs           217M     0  217M   0% /dev/shm
tmpfs           217M  3.2M  214M   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           217M     0  217M   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   40M  213M  16% /boot
tmpfs            44M     0   44M   0% /run/user/1000
```
The virtual TeslaCam folder is empty, and there are 438 files in Recent Clips. 

I'll try setting it to 1 day; my assumption is that, if I park at (wifi location) every evening->morning, there should still be enough time to sync everything off?

**Comment by wurmr** [comment]
The virtual drive drops offline every hour(?) to cycle a new drive in place. That is by design.

Do you have the rsync container syncing off RecentClips or only SavedClips?

**Comment by rtgoodwin** [comment]
I'm using the default from the current install instructions, so, good point, that appears to only tackle SavedClips? In theory that's what I care most about anyway, whether manual, or--I assume--Sentry events. 

I did tail the logs for both rsync and clean, and they're looping as expected. 
```
Running  [rsync --remove-source-files -avhe ssh /video/SavedClips richard@172.16.1.100:~/TeslaCam]
======================= Success
building file list ... done

sent 75 bytes  received 20 bytes  63.33 bytes/sec
total size is 0  speedup is 0.00
```
```
Running  [find /video/RecentClips -mtime +1 -type f -delete]
(node:1) ExperimentalWarning: The fs.promises API is experimental
Running  [find /video/RecentClips -mtime +1 -type f -delete]
```

So I'll go with the working theory that somehow I filled the card in two days. 

Edit 2: It might be nice to timestamp the log lines for going back to look at them.

**Comment by wurmr** [comment]
`docker logs` will add timestamps if you add the `-t` switch.

**Comment by rtgoodwin** [comment]
Update: with it set to 1 day, it's been stable, so I'm going to give this just a day or two more and then close it. Great work, and the most stable implementation so far!

**Comment by rtgoodwin** [comment]
Well the drive went offline and didn't come back in a hour drive. Finally got it to computer and space isn't an issue, and after about 20 mins it came online. Closing this issue since, if there's a bug, it's not this.
