### ISSUE TITLE
Possible to not have to swap two volumes?

### ISSUE THREAD

**Issue by epheterson** [milesburton/teslacam#19]
Since the Pi is simulating a USB drive, and the Tesla will likely never try to read the files after writing, would it be possible for it to simulate more than what's actually available and let the car continuously write? This would require some clever logic to handle the writes.

Or what if the Pi copied over and deleted video on the fly, in real-time as the car is writing to the same volume.

**Comment by milesburton** [comment]
I've made a mention to this in the README.md, and the short answer is no.

There may have been a possibility for EXT4, but that's also a no go => https://unix.stackexchange.com/questions/68790/can-the-same-ext4-disk-be-mounted-from-two-hosts-one-readonly

Closest thing to real time would be to use something like an Octopi or Rpi4 and mount a ramdisk that is switched out every minute or two - but that would likely lead to problems
