### ISSUE TITLE
Camera X Issue

### ISSUE THREAD

**Issue by omarqazi** [milesburton/teslacam#2]
Hey,

I haven't actually tried your code, but wanted to ask for help.

After the latest update with Sentry mode, have you been able to get the Tesla to write to the raspberry pi without showing the "Camera with X" icon

**Comment by milesburton** [comment]
Sentry hasn't been released in my region yet so I'm not sure. This aside, I have noticed on recent updates the power the USB ports can provide appears to have dropped meaning the Pi becomes unstable. I haven't had a change to do any tests, so take this with a big fat pinch of salt.
