### ISSUE TITLE
Install process not working

### ISSUE THREAD

**Issue by pepperm2** [milesburton/teslacam#21]
Sorry to trouble you but I am trying to configure a Raspberry Pi Zero W for use with a friends Tesla Model 3. Unfortunately, although I have installed Rasbian on the Pi, can SSH into it etc, I cannot beyond step 3 of your instructions in the “ On your TeslaCam Pi (via SSH)” stage of the install shown on your GitHub page (https://github.com/milesburton/teslacam). I think that the curl command is failing.

**Comment by milesburton** [comment]
I can see the issue, the readme referred to the feature branch not master. I've updated it. Try again and let us know how you get on

**Comment by pepperm2** [comment]
Thanks for that, it's getting a bit further now but not completing as can be seen below. Note also I have to 'sudo' the commands or else nothing happens. Is this correct and is the version 18.06 incorrect in the script?

pi@raspberrypi:~ $ GET_TESLACAM='mktemp' \                                      
> sudo curl -fsSL https://git.io/JeWlq -o ${GET_TESLACAM} && \
> sudo sh ${GET_TESLACAM} && \
> sudo rm ${GET_TESLACAM}
Installing TeslaCam
 Executing docker install script, commit: f45d7c11389849ff46a6b4d94e0dd1ffebca32c1
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
INFO: Searching repository for VERSION '18.06.*'
INFO: apt-cache madison 'docker-ce' | grep '18.06.*.*-0~raspbian' | head -1 | awk '{$1=$1};1' | cut -d' ' -f 3

ERROR: '18.06.*' not found amongst apt-cache madison results

**Comment by milesburton** [comment]
Let's page @wurmr. I'm not too familiar with this part of the code, we were in the process of merging a single mechanism for installation.

**Comment by milesburton** [comment]
In the mean time you may want to checkout a slightly different solution I was working with here => https://github.com/milesburton/teslacam/tree/add-ext4-filesystem

**Comment by wurmr** [comment]
@pepperm2 What version of Raspbian did you install?

When I wrote this script, docker didn't work on Buster yet. I will try to verify if it does or does not tonight.

Edit: added question rational

**Comment by pepperm2** [comment]
Arhhh, I installed the latest Rasbian Buster

**Comment by milesburton** [comment]
@pepperm2 Can we close this ticket?

**Comment by wurmr** [comment]
@milesburton leave it open, I might have a PR incoming if it works with Buster now (and it likely will).

**Comment by milesburton** [comment]
No problem, there's a number of things I've been meaning to try. There are only a few k of Model 3s in the UK, I really could do with borrowing one to see the differences Vs. the MS

**Comment by wurmr** [comment]
Tested and working on Buster, PR is in #22
