### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by simonset** [milesburton/teslacam#7]
Could you update the install instructions to be more detailed? I have minimal knowledge of using the command line and I got stuck on node install. I'm also not sure if after booting the PI for the first time if that removes my ability to see the filesystem when plugged into the data port and connected to a windows machine.

**Comment by milesburton** [comment]
Minor improvements have been made, I haven't had the time to go through it in detail as there's some bugs that have been introduced with the latest Tesla firmware which I'm investigating

**Comment by wurmr** [comment]
I've got a working branch that runs everything in containers.

It greatly simplifies installation as you just have to install docker and it handles everything else. Also it allows a smaller footprint and easier management (no need to do developer-y things like `git clone`).

I'm currently running this branch on my car, PR will be coming after discussion. I'll link here as that arrives.

Link to branch for those who want to play:
https://github.com/wurmr/teslacam/tree/feature/containerize-dashcam-monitor

**Comment by milesburton** [comment]
Oh that's pretty cool, good job.

**Comment by milesburton** [comment]
To make this a little easier I've finished up a first cut of a disk image creation script. It must be run on Linux (or a raspberry pi).

https://github.com/milesburton/teslacam/tree/add-ext4-filesystem

I'll merge this into master once I'm happy it works
