### ISSUE TITLE
Does not copy files from images

### ISSUE THREAD

**Issue by wurmr** [milesburton/teslacam#9]
When the dashcam-monitor mounts an image and looks for files it always reports 0 files. This seems to be because the countFiles function returns 0. Tesla now always has two directories under TeslaCam (SavedClips and RecentClips).

Changing the following like from `.isFile` to `.isDirectory` fixes this but I am unsure if that is the right direction to go.

https://github.com/milesburton/teslacam/blob/8ae79e31c9bc4bae2cbce0aef670616b7a6190d7/src/dashcam-monitor.js#L53

Opening this issue for conversation and to track a PR.

**Comment by milesburton** [comment]
Should be fixed here: https://github.com/milesburton/teslacam/tree/fix-recursive-paths

I'm still testing this branch.

**Comment by wurmr** [comment]
Excellent, is there anything I can do to help test or assist in the code?

Model 3 here as a testbed.

**Comment by milesburton** [comment]
> Excellent, is there anything I can do to help test or assist in the code?
> 
> Model 3 here as a testbed.

You'd be making my life a 100x easier if you could check out the branch I mentioned above and burn that to a fast SDHC card and see what it does.

If you can poke around and see if any changed you make results in a different outcome that would be helpful. Currently I've been comparing a standard USB drive vs. the TeslaCam and I've struggled to see a difference  - I did wonder if the USB serial number or other information was bleeding through and maybe Tesla blocked it for security reasons.

Given the car doesn't offer any diagnostics to us mere humans, it's somewhat trial and error. 

The car has absolutely mounted the pi with the above branch mounted, but after some time it dropped out. (I've also seen this on standard USB flash drives, so it could be unrelated).

Any help would be appreciated, once this is up and running again it opens up some cool prospects
